---
- name: restart openvpn-server
  systemd:
    name: openvpn-server@otus.local
    state: restarted


- name: restart openvpn-client
  systemd:
    name: openvpn-client@otus.local
    state: restarted
