---
- name: install PostgreSQL repos
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present


- name: install packages
  yum:
    name:
      - postgresql12-server
      - python-psycopg2
    state: present


- name: check exist pg_hba.conf
  stat:
    path: /var/lib/pgsql/12/data/pg_hba.conf
  register: pg_hba


- name: init postgresql db
  command: '/usr/pgsql-12/bin/postgresql-12-setup initdb'
  when: pg_hba.stat.exists == false


- name: copy configs
  copy: src={{ item }} dest=/var/lib/pgsql/12/data/
  with_items:
    - pg_hba.conf
    - postgresql.conf
  notify: restart postgresql


- name: start and enable service
  systemd:
    name: postgresql-12
    state: started
    enabled: yes
