---
- name: 'filebeat : configure Elastic repo'
  yum_repository:
    name: elasticsearch-7.x
    file: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: no
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    repo_gpgcheck: no


- name: 'filebeat : install packages'
  yum:
    name: filebeat
    state: present


- name: 'filebeat : copy config file'
  copy:
    src: filebeat.yml
    dest: /etc/filebeat
  notify: restart filebeat


- name: 'filebeat : enable nginx module'
  copy:
    src: nginx.yml
    dest: /etc/filebeat/modules.d
  notify: restart filebeat


- name: 'filebeat : start and enable service'
  systemd:
    name: filebeat
    state: started
    enabled: yes
