NODES = {
	:n1 => {
		:node_box  => 'centos/7',
		:node_name => 'web',
		:node_cpu  => 1,
		:node_mem  => 512,
		:node_nets => [
		],
		:node_port_fwd => [
			{ guest: 10001, host: 10001, protocol: 'tcp' },
			{ guest: 10002, host: 10002, protocol: 'tcp' },
			{ guest: 10003, host: 10003, protocol: 'tcp' }
		],
		:storages  => {
		}
	}
}


Vagrant.configure("2") do |config|

	NODES.each do |node, node_config|

		config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: ['*.vdi', '.git']

		config.vm.define node_config[:node_name] do |node|

			node.vm.box = node_config[:node_box]
			node.vm.hostname = node_config[:node_name]
			node_config[:node_nets].each do |net_config|
				node.vm.network "private_network", net_config
			end

			node.vm.provider 'virtualbox' do |vb|
				vb.name = node_config[:node_name]
				vb.cpus = node_config[:node_cpu]
				vb.memory = node_config[:node_mem]

				needSATA = false

                                node_config[:node_port_fwd].each do |port_config|
                                        node.vm.network "forwarded_port", port_config
                                end

				node_config[:storages].each do |stor, stor_config|
					unless File.exist?(stor_config[:stor_file])
						vb.customize ['createmedium', 'disk', \
						                              '--filename', stor_config[:stor_file], \
						                              '--size', stor_config[:stor_size] * 1024]
						needSATA = true
					end
				end

				if needSATA == true
					vb.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata']

					node_config[:storages].each do |stor, stor_config|
						vb.customize ['storageattach', :id, \
					    	                           '--storagectl', 'SATA', \
					        	                       '--port', stor_config[:stor_port], \
					            	                   '--device', 0, \
					                	               '--type', 'hdd', \
					                    	           '--medium', stor_config[:stor_file]]
					end
				end
			end
		end
	end

	config.vm.provision "ansible", type: :ansible, playbook: "provisioning/lesson-33.yml"
end
