MS_HOME = ''

NODES = {
	:n1 => {
		:node_box  => 'centos/7',
		:node_name => 'lesson-02',
		:node_cpu  => 4,
		:node_mem  => 2560,
		:storages  => {
			:disk1 => {
				:stor_port => 1,
				:stor_file => 'disk1.vdi',
				:stor_size => 20
			},
			:disk2 => {
				:stor_port => 2,
				:stor_file => 'disk2.vdi',
				:stor_size => 20
			},
			:disk3 => {
				:stor_port => 3,
				:stor_file => 'disk3.vdi',
				:stor_size => 20
			}	
		}
	}
}


Vagrant.configure("2") do |config|

	NODES.each do |node, node_config|

		config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: ['*.vdi', '.git']

		config.vm.define node_config[:node_name] do |node|

			node.vm.box = node_config[:node_box]
			node.vm.hostname = node_config[:node_name]

			node.vm.provider 'virtualbox' do |vb|
				vb.name = node_config[:node_name]
				vb.cpus = node_config[:node_cpu]
				vb.memory = node_config[:node_mem]

				needSATA = false
				
				node_config[:storages].each do |stor, stor_config|
					unless File.exist?(stor_config[:stor_file])
						vb.customize ['createmedium', 'disk', \
						                              '--filename', stor_config[:stor_file], \
						                              '--size', stor_config[:stor_size] * 1024]	
						needSATA = true
					end
				end

				if needSATA == true
					vb.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata']

					node_config[:storages].each do |stor, stor_config|
						vb.customize ['storageattach', :id, \
					    	                           '--storagectl', 'SATA', \
					        	                       '--port', stor_config[:stor_port], \
					            	                   '--device', 0, \
					                	               '--type', 'hdd', \
					                    	           '--medium', stor_config[:stor_file]]
					end
				end
			end
		end

		config.trigger.after [:up, :provision] do |trigger|
			trigger.info = 'Remove default hard disk from VM'
			trigger.run = {path: 'after_provision.sh'}
		end

		config.vm.provision :ansible do |ansible|
			ansible.playbook = 'provisioning/lesson-02.yml'
		end
	end
end
