---
- name: copy dump to temporary file
  copy:
    src: bet.dmp.gz
    dest: /tmp/


- name: import db
  mysql_db:
    state: import
    name: bet
    login_password: '{{ mysql_root_password }}'
    target: /tmp/bet.dmp.gz


- name: copy replica config file
  copy:
    src: replica.cnf
    dest: /etc/my.cnf.d/
  notify: restart mysqld


- name: create replica user
  mysql_user:
    login_password: '{{ mysql_root_password }}'
    name: replica
    host: '%'
    password: '{{ mysql_replica_password }}'
    priv: '*.*:REPLICATION SLAVE'
    state: present
