---
- name: 'disable default router for eth0'
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DEFROUTE='
    line: DEFROUTE="no"
  notify: restart network


- name: 'copy network config file'
  copy: src={{ item }} dest=/etc/sysconfig/network-scripts/
  with_items:
    - ifcfg-vlan22
  notify: restart network
