---
- name: install EPEL repo
  yum:
    name: epel-release
    state: present


- name: install nginx
  yum:
    name:
      - nginx
      - libsemanage-python
    state: present


- name: configure SELinux
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes


- name: copy configs
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'fastcgi.conf.j2', dest: '/etc/nginx/fastcgi.conf' }
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
  notify: restart nginx


- name: start and enable service
  systemd:
    name: nginx
    state: started
    enabled: yes
